### ISSUE TITLE
help me debugging or fixing this issue

### ISSUE THREAD

**Issue by avkoval** [emacs-helm/helm-pass#3]
I am experiencing issue that candidates list after some time working with emacs disappears, only empty list appears.

I've tried to report it here: https://github.com/emacs-helm/helm/issues/2157 but may be its something which helm-pass is responsible for.

Could you please help me debugging it? What/how I should report here?

**Comment by Ambrevar** [comment]
I can't reproduce.
Is `pass` (the system program) working properly for you?

Can you enable `toggle-debug-on-error` in Emacs and report the backtrace (if any) when running

```
M-: (password-store-list)
```
?

Thanks!

**Comment by avkoval** [comment]
(password-store-list) works fine when I try it, it was explained in original bug report. I can't reproduce this reliably, this is the problem. Moreover, it does not seems that it is only helm-pass problem, on that computer where it happens it happen also to helm-org-in-buffer-headings.

So... I probably will try to use  @thierryvolpiatto instructions and debug it on helm-pass, but since its not stable I am closing this issue until I've got more evidence. Thank you for your reply!
