### ISSUE TITLE
Copies to kill ring, not clipboard

### ISSUE THREAD

**Issue by micah** [emacs-helm/helm-pass#5]
First - thanks for making helm-pass, just what I was looking for!

Secondly, I notice that if I hit enter on an entry, that it is copied to the emacs kill-ring, but it is not entered into my clipboard.  This makes it so the password is only available as a yank/put in emacs, but I cannot use it outside of emacs.

Is there a way to get it also into the clipboard?

The function that helm-password calls is `password-store-copy` which is described as:

```
password-store-copy is an interactive autoloaded compiled Lisp function in
‘password-store.el’.

(password-store-copy ENTRY)

Add password for ENTRY into the kill ring.

Clear previous password from the kill ring.  Pointer to the kill ring
is stored in ‘password-store-kill-ring-pointer’.  Password is cleared
after ‘password-store-time-before-clipboard-restore’ seconds.
```

Thanks!

**Comment by micah** [comment]
Maybe what should be used is `clipboard-kill-ring-save`:

```
clipboard-kill-ring-save is an interactive compiled Lisp function in
‘menu-bar.el’.

It is bound to <copy>, <f16>.

(clipboard-kill-ring-save BEG END &optional REGION)

Copy region to kill ring, and save in the GUI’s clipboard.
If the optional argument REGION is non-nil, the function ignores
BEG and END, and saves the current region instead.
```

**Comment by thierryvolpiatto** [comment]
micah <notifications@github.com> writes:

> Is there a way to get it also into the clipboard?

M-x helm-show-kill-ring and C-c C-k.
Now your entry in on clipboard.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by micah** [comment]
@thierryvolpiatto indeed, that does work - but its quite a bit to type to get something into my clipboard. First, I must M-x helm-pass, then type the pattern, <ENTER> M-x helm-show-kill-ring C-c C-k. 

Would be nice to cut that down a bit...

**Comment by thierryvolpiatto** [comment]
micah <notifications@github.com> writes:

> @thierryvolpiatto indeed, that does work - but its quite a bit to type
> to get something into my clipboard. First, I must M-x helm-pass, then
> type the pattern, M-x helm-show-kill-ring C-c C-k.
>
> Would be nice to cut that down a bit...

If you have to C-c C-k from helm-show-kill-ring, perhaps you have
modified `select-enable-clipboard` or some other variables managing
clipboard?

You can check easily:

1) Eval (kill-new "foo") in scratch buffer.
2) Open firefox (or whatever external program) and hit C-v.
What do you see?


--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by micah** [comment]
> If you have to C-c C-k from helm-show-kill-ring, perhaps you have modified `select-enable-clipboard` or some other variables managing clipboard? 

Well, you are the one who said:

> M-x helm-show-kill-ring and C-c C-k. Now your entry in on clipboard.

so I'm a little confused what you mean.

>You can check easily:
>
>1) Eval (kill-new "foo") in scratch buffer.
2>) Open firefox (or whatever external program) and hit C-v.

foo

**Comment by thierryvolpiatto** [comment]
If kill-new is pushing to clipboard that's mean helm-pass should work as expected as it seems it is using kill-new internally.
Maybe you are killing something else before trying to paste in external application?
@Ambrevar ?

**Comment by micah** [comment]
Thanks, I think maybe this isn't a problem with helm-pass, I'll look into my setup more, thanks!
