### ISSUE TITLE
Accept “login” as Equivalent of “Username”

### ISSUE THREAD

**Issue by baums** [emacs-helm/helm-pass#7]
The pass-import plugin (https://github.com/roddhjav/pass-import) saves usernames under the heading “login”:

    login: me@example.com

rather than “Username”:

    Username: me@example.com

As a consequence, helm-pass’s “Copy username to clipboard” fails with “Username not found!” Please accept “login” as well as “Username.”

**Comment by baums** [comment]
Cf. this issue: https://github.com/roddhjav/pass-import/issues/135

**Comment by jasbrg** [comment]
I made a pull request that solves this in a way, by adding another dialog to select from the secret's fields: #8

**Comment by Ambrevar** [comment]
Closed with #8.
