### ISSUE TITLE
Incorrect $EDITOR is being used

### ISSUE THREAD

**Issue by zamlz** [emacs-helm/helm-pass#9]
Based on my understanding of the [`with-editor`](https://github.com/magit/with-editor/tree/36e163ca80f74905ba3c1cf7b596a0ccc8bc5cac) package, when editing the entry found here, it should open them through the emacsclient.

So the issue I'm facing is that it is opening it in my system's default `$EDITOR` which is vi. However this should have been overriden right? I can confirm that `magit` which uses this library is able to edit commit messages in a valid emacs text buffer for editing. I also have it setup so that `vterm` as well also opens any files I want to edit in emacs properly as well.

Would appreciate you're help to getting to the bottom of this as I'm unsure if this is a bug in the package or something else wrong in my configuration perhaps.

Thanks!

- zamlz

**Comment by Ambrevar** [comment]
What do you mean with 

> when editing the entry found here,

?

What are you trying to achieve?

**Comment by Ambrevar** [comment]
If you are talking about the "Edit entry" action (`f3`), it's just a call to `password-store-edit` which comes from the password-store.el library.

If this misbehaves for you, you should report upstream.  See http://www.passwordstore.org/.

**Comment by zamlz** [comment]
Yeah looks like that function is misbehaving alright.
Regarding your question, its when I use the edit action on the candidate in
helm.
In any case, like you said its an upstream issue.

**Comment by Ambrevar** [comment]
Thanks for confirming.  Feel free to reopen if you have more questions.
